### ISSUE TITLE
Issue with windows build for Maya 2018

### ISSUE THREAD

**Issue by krzymRR** [chadmv/cmt#4]
Hello,
I've issues building with CMake:

`D:\Dropbox (Siekiera)\maya_scripts\cmt-master3\build.2018>cmake --build  .  --config Release
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  rbfNode.cpp
D:\Dropbox (Siekiera)\maya_scripts\cmt-master3\src\rbfNode.cpp(581): error C2039: 'asDouble4': is not a member of 'Autodesk::M
aya::OpenMaya20180000::MDataHandle' [D:\Dropbox (Siekiera)\maya_scripts\cmt-master3\build.2018\src\cmt.vcxproj]
  C:\Program Files\Autodesk\Maya2018\include\maya/MDataHandle.h(75): note: see declaration of 'Autodesk::Maya::OpenMaya2018000
  0::MDataHandle'
D:\Dropbox (Siekiera)\maya_scripts\cmt-master3\src\rbfNode.cpp(581): error C2530: 'values': references must be initialized [D:
\Dropbox (Siekiera)\maya_scripts\cmt-master3\build.2018\src\cmt.vcxproj]`

Any chance you'd know what I'm doing wrong?
Thanks in advance!
K

**Comment by chadmv** [comment]
Looks like asDouble4 wasn't added to MDataHandle until later, I'll need to update to support 2018.

**Comment by syoyo** [comment]
https://github.com/syoyo/cmt/commit/61370e3f2cfc715396506f09c3042b6aee1480d3

Here is a possible fix. If this looks ok, I can send a PR
